# Generated by Django 2.0 on 2021-01-23 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('url', models.URLField(max_length=2083, verbose_name='URL')),
                ('background_color', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'link',
            },
        ),
    ]
